export const FETCH_KITS = 'FETCH_KITS';
export const SELECTED_KIT = 'SELECTED_KIT';

export const KITS = 'KITS';
export const GET_KITS_START = 'GET_KITS_START';
export const GET_KITS_SUCCESS = 'GET_KITS_SUCCESS';
export const GET_KITS_FAILURE = 'GET_KITS_FAILURE';

export const KIT_DETAILS = 'KITS_DETAILS';
export const GET_KIT_DETAILS_START = 'GET_KITS_DETAILS_START';
export const GET_KIT_DETAILS_SUCCESS = 'GET_KITS_DETAILS_SUCCESS';
export const GET_KIT_DETAILS_FAILURE = 'GET_KITS_DETAILS_FAILURE';

export const KITS_THEMES = 'KITS_THEMES';
export const GET_KITS_THEMES_START = 'GET_KITS_THEMES_START';
export const GET_KITS_THEMES_SUCCESS = 'GET_KITS_THEMES_SUCCESS';
export const GET_KITS_THEMES_FAILURE = 'GET_KITS_THEMES_FAILURE';

export const KITS_LOCATIONS = 'KITS_LOCATIONS';
export const GET_KITS_LOCATIONS_START = 'GET_KITS_LOCATIONS_START';
export const GET_KITS_LOCATIONS_SUCCESS = 'GET_KITS_LOCATIONS_SUCCESS';
export const GET_KITS_LOCATIONS_FAILURE = 'GET_KITS_LOCATIONS_FAILURE';

export const ADMIN_USER_ID = 'ADMIN_USER_ID';

export const GET_ADMIN_USER_START = 'GET_ADMIN_USER_START';
export const GET_ADMIN_USER_SUCCESS = 'GET_ADMIN_USER_SUCCESS';
export const GET_ADMIN_USER_FAILURE = 'GET_ADMIN_USER_FAILURE';

export const MODIFY_ADMIN_USER_START = 'MODIFY_ADMIN_USER_START';
export const MODIFY_ADMIN_USER_SUCCESS = 'MODIFY_ADMIN_USER_SUCCESS'; 
export const MODIFY_ADMIN_USER_FAILURE = 'MODIFY_ADMIN_USER_FAILURE' 